# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FloodModellingTools
                                 A QGIS plugin
 get description here
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-06-08
        copyright            : (C) 2021 by Carlos Eduardo Mota
        email                : carlos.mota@cprm.gov.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Carlos Eduardo Mota'
__date__ = '2021-06-08'
__copyright__ = '(C) 2021 by Carlos Eduardo Mota'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FloodModellingTools class from file FloodModellingTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fmt import FloodModellingToolsPlugin
    return FloodModellingToolsPlugin()
